enum AppMode{
  DEBUG,
  RELEASE
}

AppMode APP_MODE = AppMode.DEBUG;

enum HomeScreenMode {
  ADDRESS_EMPTY,
  MENU_SELECTED,
  AFTER_DELIVERY_LUNCH,
  AFTER_DELIVERY_DINNER,
  ON_DELIVERY_LUNCH,
  ON_DELIVERY_DINNER,
  MENU_EMPTY,
}

HomeScreenMode HOME_SCREEN_MODE = HomeScreenMode.ADDRESS_EMPTY;